# Generated by Django 3.2.4 on 2021-06-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255, unique=True)),
                ('Numero_almacen', models.IntegerField()),
                ('Imagen_Perfil', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Almacenes',
                'verbose_name_plural': 'Almacen',
            },
        ),
        migrations.CreateModel(
            name='Calidad_Control_Lotes_Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_de_Pedio_Calidad', models.CharField(max_length=255, null=True, unique=True)),
                ('Numero_Lote', models.IntegerField()),
                ('Fecha_registro', models.DateField()),
                ('Fecha_programada_de_pruebas', models.DateField(null=True)),
                ('Motivo', models.TextField()),
                ('Numero_de_productos', models.IntegerField()),
                ('Enviado_Pruebas', models.BooleanField(default=False)),
                ('Almacen_alojado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Calidad.almacen')),
            ],
            options={
                'verbose_name': 'Control de lote',
                'verbose_name_plural': 'Control de lote',
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_empleado', models.CharField(max_length=255, unique=True)),
                ('Nombre_empleado', models.CharField(max_length=255)),
                ('Apellido_empleado', models.CharField(max_length=255)),
                ('Puesto_empleado', models.CharField(max_length=255)),
                ('Fecha_registro', models.DateField()),
                ('Imagen_Perfil', models.URLField(null=True)),
            ],
            options={
                'verbose_name': 'Empleados',
                'verbose_name_plural': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255, unique=True)),
                ('Fecha_ingreso', models.DateField()),
            ],
            options={
                'verbose_name': 'Productos',
                'verbose_name_plural': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Calidad_Pruebas_Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Prueba', models.CharField(max_length=255)),
                ('Numero_de_Prueba', models.IntegerField()),
                ('Tipo_de_pruebas', models.CharField(max_length=255)),
                ('Pruebas_satisfactorias', models.BooleanField(default=False, null=True)),
                ('Fecha_programada_de_pruebas', models.DateField(null=True)),
                ('Enviado_Liberacion', models.BooleanField(default=False, null=True)),
                ('Encargado_de_pruebas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Calidad.empleados')),
                ('Numero_de_Lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Calidad.calidad_control_lotes_registro')),
            ],
            options={
                'verbose_name': 'Pruebas',
                'verbose_name_plural': 'Prueba',
            },
        ),
        migrations.CreateModel(
            name='Calidad_Liberacion_Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_de_liberacion', models.CharField(max_length=255, null=True, unique=True)),
                ('Numero_liberacion', models.IntegerField()),
                ('Fecha_liberacion', models.DateField()),
                ('Notas', models.TextField()),
                ('Enviado_almacen', models.BooleanField(default=False)),
                ('Validado', models.BooleanField(default=False)),
                ('Devueltos_a_pruebas', models.BooleanField(default=False)),
                ('Encargado_de_liberacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Calidad.empleados')),
                ('Lote_liberado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Calidad.calidad_control_lotes_registro')),
            ],
            options={
                'verbose_name': 'Liberacion',
                'verbose_name_plural': 'Liberaciones',
            },
        ),
        migrations.AddField(
            model_name='calidad_control_lotes_registro',
            name='Encargado_de_control_lotes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Calidad.empleados'),
        ),
        migrations.AddField(
            model_name='calidad_control_lotes_registro',
            name='Productos',
            field=models.ManyToManyField(to='Control_Calidad.Producto'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='Encargado_de_almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Control_Calidad.empleados'),
        ),
    ]
